import mongoose from "mongoose";

/**
 * Insight Model - Actionable insights generated by rules engine
 * Provides intelligent analysis of user progress and activity
 */
const insightSchema = new mongoose.Schema({
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: "User", 
    required: true,
    index: true 
  },
  
  // Insight classification
  type: { 
    type: String, 
    enum: [
      "rating_stagnant",      // CF rating unchanged for extended period
      "topic_strength",       // Strong performance in specific topic
      "topic_weakness",       // Weak performance in specific topic
      "activity_drop",        // Significant activity decrease
      "streak_alert",         // Streak broken or at risk
      "milestone_reached",    // Achievement unlocked
      "consistency_praise",   // Consistent activity pattern
      "rating_improvement",   // Significant rating gain
      "problem_recommendation" // Suggested focus area
    ], 
    required: true 
  },
  
  // Associated platform (optional - some insights are cross-platform)
  platform: { 
    type: String, 
    enum: ["leetcode", "codeforces", "github", "codechef", "atcoder", null], 
    default: null 
  },
  
  // Human-readable insight message
  title: {
    type: String,
    required: true
  },
  message: { 
    type: String, 
    required: true 
  },
  
  // Structured data for frontend rendering
  data: { 
    type: Object, 
    default: {} 
  },
  
  // Priority for display ordering
  priority: { 
    type: String, 
    enum: ["low", "medium", "high"], 
    default: "medium" 
  },
  
  // User interaction
  read: { 
    type: Boolean, 
    default: false,
    index: true 
  },
  dismissed: { 
    type: Boolean, 
    default: false 
  },
  
  // Expiration for time-sensitive insights
  expiresAt: { 
    type: Date, 
    default: null,
    index: true 
  },
  
  createdAt: { 
    type: Date, 
    default: Date.now,
    index: true 
  }
});

// Compound index for user insights query
insightSchema.index({ userId: 1, read: 1, createdAt: -1 });

export default mongoose.model("Insight", insightSchema);
